### ISSUE TITLE
Email Script

### ISSUE THREAD

**Issue by blissman** [GortHealth/gorthealth.github.io#1]
'mail' folder (containing php for contact form) has been removed from this deployment, rendering 'contact' section useless. Was there a reason for this?

**Comment by pilifs** [comment]
Yeah, GitHub pages doesn't support PHP, but that said I thought the script was an unused part of the original template or I wouldn't have just removed it. My bad. We can use a plugin to achieve the same thing. I'll set it up shortly.

**Comment by blissman** [comment]
Ah. Okay, I figured it was going to be something like that. Let me know if
you need any help.

**Comment by pilifs** [comment]
Should be working now so I'm going to close this :)

**Comment by blissman** [comment]
info.kinly@gmail.com has not received any emails from the website. Can you check the config?

**Comment by pilifs** [comment]
E-mail name was backwards, closing, thanks
